/**
 * Generate BOTH halves of replication from db/schema.sql:
 * the SQLite triggers that capture changes, and the Postgres DDL that
 * receives them.
 *
 * Both were hand-written first and both were wrong, in the same way:
 * guessed primary keys. capture_timing has no `id`, six tables have
 * composite keys, and a trigger naming a column that does not exist
 * fails at INSERT time rather than at schema load. So the local schema
 * is the single authority and the keys are read from it.
 *
 * Which tables replicate is a POLICY decision and stays a list here.
 * app_secret is absent on purpose: the sync token must not leave the
 * device, and the guarantee is that no mechanism exists to carry it.
 *
 *   npm run gen:replica
 */
import { createRequire } from 'node:module';
import { readFileSync, writeFileSync } from 'node:fs';

const nodeRequire = createRequire(import.meta.url);
const { DatabaseSync } = nodeRequire('node:' + 'sqlite') as { DatabaseSync: any };

const root = new URL('../', import.meta.url);
const schemaPath = new URL('db/schema.sql', root);

const MARKER = '\n-- Generated triggers.';
const REPLICATE = [
  'utterance', 'food', 'food_nutrient', 'unit', 'food_unit', 'user_measure',
  'log_entry', 'log_revision', 'phrase_index', 'daily_logging_stats',
  'workout_session', 'session_energy', 'daily_metric', 'body_profile',
  'energy_target', 'capture_timing', 'app_setting', 'imported_entry',
  'meal_slot_window', 'match_audit', 'undone_utterance', 'meal',
  'meal_component', 'satiety_rating', 'decision_log',
].sort();

const full = readFileSync(schemaPath, 'utf8');
const base = full.includes(MARKER) ? full.slice(0, full.indexOf(MARKER)) : full;

const db = new DatabaseSync(':memory:');
db.exec(base);

/** Primary key columns, in order, read from the database itself. */
function primaryKey(table: string): string[] {
  const cols = db.prepare(`PRAGMA table_info(${table})`).all() as Array<
    { name: string; pk: number }>;
  const pk = cols.filter((c) => c.pk > 0).sort((a, b) => a.pk - b.pk).map((c) => c.name);
  if (pk.length === 0) throw new Error(`${table} has no primary key; it cannot be replicated`);
  return pk;
}

// ---- the SQLite triggers ----
const triggers: string[] = [`
-- Generated triggers. Do not edit by hand: run npm run gen:replica.
--
-- One per table per operation - SQLite has no statement-level or
-- multi-table triggers, so this is verbose by necessity. Capturing
-- changes by trigger rather than by instrumenting each mutation is what
-- makes a write path that does not know replication exists still get
-- replicated.
`];
for (const table of REPLICATE) {
  const key = primaryKey(table);
  for (const [op, when, ref] of [['upsert', 'INSERT', 'NEW'], ['upsert', 'UPDATE', 'NEW'],
    ['delete', 'DELETE', 'OLD']] as const) {
    const expr = key.map((c) => `CAST(${ref}.${c} AS TEXT)`).join(" || '|' || ");
    triggers.push(`CREATE TRIGGER IF NOT EXISTS trg_${table}_${when.toLowerCase()}_repl
AFTER ${when} ON ${table} BEGIN
    INSERT INTO change_log (table_name, row_id, op, changed_at)
    VALUES ('${table}', ${expr}, '${op}', datetime('now'))
    ON CONFLICT(table_name, row_id) WHERE pushed_at IS NULL
    DO UPDATE SET op = excluded.op, changed_at = excluded.changed_at;
END;
`);
  }
}
writeFileSync(schemaPath, base + triggers.join('\n'));

// ---- the Postgres DDL ----
const pgType = (declared: string): string => {
  const t = declared.toUpperCase();
  if (t.includes('INT')) return 'integer';
  if (t.includes('REAL') || t.includes('FLOA') || t.includes('DOUB')) return 'double precision';
  return 'text';
};

const out: string[] = [`-- GENERATED by scripts/gen-replica-sql.ts. Do not edit by hand.
-- Regenerate with: npm run gen:replica
--
-- Replica of the app's local database, in Postgres.
--
-- WHO TALKS TO THIS. Only the sync server, with the service key. The
-- browser never holds a Supabase credential and never opens a
-- connection to Supabase: it posts changes to /api/replica on its own
-- origin with the bearer token it already has. That keeps connect-src
-- 'self' intact, keeps the service key out of a page anyone can view
-- source on, and means there is no anon key to leak.
--
-- SECURITY POSTURE. RLS is enabled on every table and NO POLICY IS
-- CREATED. Deliberate, not an omission: with RLS on and no policy, anon
-- and authenticated read nothing at all, while service_role bypasses
-- RLS. Default deny, and the only way in is a key held on a server.
--
-- TIMESTAMPS ARE text, NOT timestamptz. The app writes LOCAL wall time
-- with no zone suffix. Letting Postgres parse those would apply the
-- server's zone and file an IST 00:30 dinner on the previous day - a
-- bug this project has already paid for once.
`];

for (const table of REPLICATE) {
  const cols = db.prepare(`PRAGMA table_info(${table})`).all() as Array<
    { name: string; type: string }>;
  const lines = cols.map((c) => `    ${c.name} ${pgType(c.type)}`);
  lines.push('    synced_at timestamptz NOT NULL DEFAULT now()');
  lines.push(`    PRIMARY KEY (${primaryKey(table).join(', ')})`);
  out.push(`CREATE TABLE IF NOT EXISTS ${table} (\n${lines.join(',\n')});\n`);
}

out.push(`-- Default deny on every replicated table.
DO $$
DECLARE t text;
BEGIN
  FOR t IN SELECT tablename FROM pg_tables WHERE schemaname = 'public'
  LOOP
    EXECUTE format('ALTER TABLE public.%I ENABLE ROW LEVEL SECURITY', t);
    EXECUTE format('ALTER TABLE public.%I FORCE ROW LEVEL SECURITY', t);
  END LOOP;
END $$;

-- Indexes for the questions this replica exists to answer.
CREATE INDEX IF NOT EXISTS idx_log_entry_eaten ON log_entry (eaten_at);
CREATE INDEX IF NOT EXISTS idx_daily_metric_date ON daily_metric (log_date);
CREATE INDEX IF NOT EXISTS idx_body_profile_recorded ON body_profile (recorded_at);
`);
writeFileSync(new URL('db/supabase/0001_replica.sql', root), out.join('\n'));

// ---- the server's allowlist, so it cannot drift from either ----
const allow = REPLICATE.map((t) => `  ${t}: [${primaryKey(t).map((c) => `'${c}'`).join(', ')}],`);
console.log(`generated ${REPLICATE.length} tables`);
console.log('server allowlist:\n' + allow.join('\n'));
