-- GENERATED by scripts/gen-replica-sql.ts. Do not edit by hand.
-- Regenerate with: npm run gen:replica
--
-- Replica of the app's local database, in Postgres.
--
-- WHO TALKS TO THIS. Only the sync server, with the service key. The
-- browser never holds a Supabase credential and never opens a
-- connection to Supabase: it posts changes to /api/replica on its own
-- origin with the bearer token it already has. That keeps connect-src
-- 'self' intact, keeps the service key out of a page anyone can view
-- source on, and means there is no anon key to leak.
--
-- SECURITY POSTURE. RLS is enabled on every table and NO POLICY IS
-- CREATED. Deliberate, not an omission: with RLS on and no policy, anon
-- and authenticated read nothing at all, while service_role bypasses
-- RLS. Default deny, and the only way in is a key held on a server.
--
-- TIMESTAMPS ARE text, NOT timestamptz. The app writes LOCAL wall time
-- with no zone suffix. Letting Postgres parse those would apply the
-- server's zone and file an IST 00:30 dinner on the previous day - a
-- bug this project has already paid for once.

CREATE TABLE IF NOT EXISTS app_setting (
    key text,
    value text,
    synced_at timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (key));

CREATE TABLE IF NOT EXISTS body_profile (
    id integer,
    recorded_at text,
    sex text,
    age_years double precision,
    height_cm double precision,
    weight_kg double precision,
    body_fat_pct double precision,
    activity_factor double precision,
    goal_rate_kg_per_week double precision,
    goal_weight_kg double precision,
    synced_at timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (id));

CREATE TABLE IF NOT EXISTS capture_timing (
    utterance_id integer,
    mic_tap_to_stt double precision,
    stt_to_capture double precision,
    capture_to_entry double precision,
    total_ms double precision,
    fast_path integer,
    entry_count integer,
    synced_at timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (utterance_id));

CREATE TABLE IF NOT EXISTS daily_logging_stats (
    log_date text,
    entry_count integer,
    pending_count integer,
    weighed_fraction double precision,
    fastpath_fraction double precision,
    outside_food_count integer,
    first_log_at text,
    last_log_at text,
    model_eligible integer,
    synced_at timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (log_date));

CREATE TABLE IF NOT EXISTS daily_metric (
    log_date text,
    metric text,
    source text,
    value double precision,
    recorded_at text,
    synced_at timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (log_date, metric, source));

CREATE TABLE IF NOT EXISTS decision_log (
    id integer,
    issued_at text,
    kind text,
    headline text,
    because text,
    confidence text,
    predicted_metric text,
    predicted_value double precision,
    horizon_days integer,
    baseline_value double precision,
    adopted integer,
    acted_at text,
    evaluated_at text,
    observed_value double precision,
    verdict text,
    verdict_basis text,
    synced_at timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (id));

CREATE TABLE IF NOT EXISTS energy_target (
    log_date text,
    source text,
    kcal double precision,
    basis text,
    computed_at text,
    synced_at timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (log_date, source));

CREATE TABLE IF NOT EXISTS food (
    id integer,
    name text,
    brand text,
    is_composite integer,
    source text,
    source_ref text,
    source_fetched text,
    default_unit_id integer,
    created_at text,
    synced_at timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (id));

CREATE TABLE IF NOT EXISTS food_nutrient (
    food_id integer,
    nutrient text,
    per_100g double precision,
    rel_error double precision,
    synced_at timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (food_id, nutrient));

CREATE TABLE IF NOT EXISTS food_unit (
    food_id integer,
    unit_id integer,
    synced_at timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (food_id, unit_id));

CREATE TABLE IF NOT EXISTS imported_entry (
    id integer,
    source text,
    eaten_at text,
    food_text text,
    portion_text text,
    meal_label text,
    imported_at text,
    synced_at timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (id));

CREATE TABLE IF NOT EXISTS log_entry (
    id integer,
    utterance_id integer,
    eaten_at text,
    meal_slot text,
    food_id integer,
    quantity double precision,
    unit_id integer,
    grams_resolved double precision,
    status text,
    match_method text,
    match_score double precision,
    created_at text,
    synced_at timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (id));

CREATE TABLE IF NOT EXISTS log_revision (
    id integer,
    log_entry_id integer,
    revised_at text,
    field text,
    old_value text,
    new_value text,
    reason text,
    synced_at timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (id));

CREATE TABLE IF NOT EXISTS match_audit (
    id integer,
    utterance_id integer,
    log_entry_id integer,
    phrase text,
    chosen_phrase text,
    chosen_food_id integer,
    score double precision,
    runner_up text,
    runner_up_score double precision,
    threshold double precision,
    accepted integer,
    learned integer,
    decided_at text,
    synced_at timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (id));

CREATE TABLE IF NOT EXISTS meal (
    id integer,
    name text,
    slot text,
    origin text,
    created_at text,
    n_observations integer,
    last_seen_at text,
    synced_at timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (id));

CREATE TABLE IF NOT EXISTS meal_component (
    meal_id integer,
    food_id integer,
    quantity double precision,
    unit_id integer,
    synced_at timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (meal_id, food_id));

CREATE TABLE IF NOT EXISTS meal_slot_window (
    slot text,
    centre_min double precision,
    start_min double precision,
    end_min double precision,
    n_observations integer,
    derived_at text,
    derived_from text,
    synced_at timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (slot));

CREATE TABLE IF NOT EXISTS phrase_index (
    id integer,
    phrase text,
    food_id integer,
    default_qty double precision,
    default_unit_id integer,
    hit_count integer,
    last_used_at text,
    synced_at timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (id));

CREATE TABLE IF NOT EXISTS satiety_rating (
    id integer,
    eaten_at text,
    slot text,
    fullness integer,
    rated_at text,
    minutes_after double precision,
    basis text,
    synced_at timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (id));

CREATE TABLE IF NOT EXISTS session_energy (
    session_id integer,
    source text,
    kcal double precision,
    recorded_at text,
    synced_at timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (session_id, source));

CREATE TABLE IF NOT EXISTS undone_utterance (
    utterance_id integer,
    undone_at text,
    entries_removed integer,
    synced_at timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (utterance_id));

CREATE TABLE IF NOT EXISTS unit (
    id integer,
    code text,
    is_absolute integer,
    synced_at timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (id));

CREATE TABLE IF NOT EXISTS user_measure (
    id integer,
    food_id integer,
    unit_id integer,
    grams double precision,
    basis text,
    calibrated_at text,
    synced_at timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (id));

CREATE TABLE IF NOT EXISTS utterance (
    id integer,
    spoken_at text,
    tz_offset_min integer,
    raw_text text,
    stt_confidence double precision,
    audio_path text,
    processed_at text,
    synced_at timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (id));

CREATE TABLE IF NOT EXISTS workout_session (
    id integer,
    started_at text,
    duration_min double precision,
    kind text,
    notes text,
    distance_m double precision,
    avg_hr double precision,
    training_load double precision,
    aerobic_effect double precision,
    anaerobic_effect double precision,
    synced_at timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (id));

-- Default deny on every replicated table.
DO $$
DECLARE t text;
BEGIN
  FOR t IN SELECT tablename FROM pg_tables WHERE schemaname = 'public'
  LOOP
    EXECUTE format('ALTER TABLE public.%I ENABLE ROW LEVEL SECURITY', t);
    EXECUTE format('ALTER TABLE public.%I FORCE ROW LEVEL SECURITY', t);
  END LOOP;
END $$;

-- Indexes for the questions this replica exists to answer.
CREATE INDEX IF NOT EXISTS idx_log_entry_eaten ON log_entry (eaten_at);
CREATE INDEX IF NOT EXISTS idx_daily_metric_date ON daily_metric (log_date);
CREATE INDEX IF NOT EXISTS idx_body_profile_recorded ON body_profile (recorded_at);
